export default {
    MOVIES: 'MOVIES',
    CURRENT_PAGE: 'CURRENT_PAGE',
    TOGGLE_LOADER: 'TOGGLE_LOADER',
    REMOVE_MOVIE: 'REMOVE_MOVIE',
    TOGGLE_TITLE: 'TOGGLE_TITLE',
    SHOW_TOAST_NOTIFICATION: 'SHOW_TOAST_NOTIFICATION'
}